Lx: 1.         # length of mesh
Ly: 0.5        # height of mesh
nx: 100        # number of cells in x
totaltime: 8.0 # duration of simulations
dt: 1.e-2      # timestep
checkpoint: 1.e0 # time interval to checkpoint data and restart
kappa: 0.0004  # gradient energy coefficient
script: explicitDW7a.py # script to iterate on that does actual calculations
